  ---- from the book All About Maude
  ---- from the Maude Manual
  ---- by the Maude team

  fmod SIMPLE-NAT-LIST is
    protecting NAT .
    sort NatList .
    subsort Nat < NatList .
    op __ : NatList NatList -> NatList [assoc] .
  endfm

  fmod NAIVE-SORTED-NAT-LIST is
    protecting SIMPLE-NAT-LIST .
    sort SortedNatList .
    subsort Nat < SortedNatList < NatList .

    vars I J : Nat .
    var  SNL : SortedNatList .
    cmb I J : SortedNatList if I <= J .
    cmb I J SNL : SortedNatList if I <= J /\ J SNL : SortedNatList .
  endfm

***(
Maude> red 0 1 2 3 4 5 6 7 8 9 .
Warning: membership axioms are not guaranteed to work correctly for associative
    symbol __ as it has declarations that are not at the kind level.
reduce in NAIVE-SORTED-NAT-LIST : 0 1 2 3 4 5 6 7 8 9 .
rewrites: 1354 in 0ms cpu (3ms real) (~ rewrites/second)
result SortedNatList: 0 1 2 3 4 5 6 7 8 9
)