#!/usr/bin/env bash

top_dir="$(pwd)"
build_dir="$top_dir/.build"
include_dir="$build_dir/include"
lib_dir="$build_dir/lib"

automake --add-missing
aclocal
autoconf
autoheader
automake

./configure --without-cvc4 "$@"

make -s -j4

git checkout -- src/Mixfix/surface.cc

make -s -j4
