#!/usr/bin/env bash

export CXXFLAGS="-std=c++14 -Wall $CFLAGS"

automake --add-missing

aclocal \
    && autoconf \
    && autoheader \
    && automake \
    && ./configure \
    && make -s -j4

git checkout -- src/Mixfix/surface.cc

make -s -j4
