#!/bin/sh

MAUDE_LIB=$srcdir/../../../src/Main
export MAUDE_LIB

../../../src/Main/maude \
  < $srcdir/bakery.maude -no-banner -no-advise \
  > bakery.out 2>&1

diff $srcdir/bakery.expected bakery.out > /dev/null 2>&1
