#!/bin/sh

MAUDE_LIB=$srcdir/../../../src/Main
export MAUDE_LIB

../../../src/Main/maude \
  < $srcdir/dijkstra-mutex.maude -no-banner -no-advise \
  > dijkstra-mutex.out 2>&1

diff $srcdir/dijkstra-mutex.expected dijkstra-mutex.out > /dev/null 2>&1
