#!/bin/sh

MAUDE_LIB=$srcdir/../../../src/Main
export MAUDE_LIB

../../../src/Main/maude \
  < $srcdir/rw.maude -no-banner -no-advise \
  > rw.out 2>&1

diff $srcdir/rw.expected rw.out > /dev/null 2>&1
