#!/bin/sh

MAUDE_LIB=$srcdir/../../../src/Main
export MAUDE_LIB

../../../src/Main/maude \
  < $srcdir/token-mutex.maude -no-banner -no-advise \
  > token-mutex.out 2>&1

diff $srcdir/token-mutex.expected token-mutex.out > /dev/null 2>&1
