--- Load Systems and Prelude
--- ------------------------

set show timing off .

load ../../../contrib/systems/cycle.maude
load ../../../contrib/tools/base/prelude.maude

--- Module BOUND
--- ------------

select BOUND .

reduce not (unbounded < 3) .
reduce 3 < unbounded .
reduce (unbounded < unbounded =/= true) and (unbounded < unbounded =/= false) .

reduce continue(3, 5)         == 4, 5 .
reduce continue(3, unbounded) == 4, unbounded .
reduce      continue(3, 4)                 :: Depth .
reduce      continue(3, unbounded)         :: Depth .
reduce not (continue(unbounded, unbounded) :: Depth) .
reduce not (continue(5, 3)                 :: Depth) .

--- Module META-LEVEL
--- -----------------

select META-LEVEL .

reduce metaNarrowingApply(upModule('EXT-CYCLE, true), 'f['a.PreState], empty, '#, 0)
    == { 'f['b.PreState] ,'State , [] , 'a2b,(none).Substitution,(none).Substitution , '% } .

reduce metaNarrowingApply(upModule('EXT-CYCLE, true), 'f['a.PreState], empty, '#, 1)
    == { 'g['c.PreState] ,'State , [] , 'a2c ,(none).Substitution ,(none).Substitution , '% } .

reduce metaNarrowingApply(upModule('EXT-CYCLE, true), 'f['a.PreState], empty, '#, 2)
    == (failure).NarrowingApplyResult? .
