#!/bin/sh

MAUDE_LIB=$srcdir/../../../src/Main
export MAUDE_LIB

../../../src/Main/maude \
  < preludeTests.maude -no-banner -no-advise \
  > preludeTests.out 2>&1

diff preludeTests.expected preludeTests.out > /dev/null 2>&1
