set show timing off .

load ../../contrib/systems/caut.maude

fmod 5x5GRID is
    including PERIODIC-GRID .

    var S : State . var SS : States .

    --- calculate the next state as a function of the neighborhood

   ops X - : -> State .
   --------------------

    eq width  = 3 .
    eq height = 3 .

    eq S -> up[X] down[X]                  SS = S -> X .
    eq S ->               left[-] right[X] SS = S -> X .
    eq - -> up[-]         left[-] right[-] SS = - -> X .
    eq S ->                                SS = S -> - [owise] .

    --- generate a random 5X5 grid

    var N : Nat .

    op init : Nat -> Culture .
    --------------------------
    eq init(0)
     = (0, 0) :: - ; (0, 1) :: X ; (0, 2) :: -
     ; (1, 0) :: X ; (1, 1) :: - ; (1, 2) :: -
     ; (2, 0) :: X ; (2, 1) :: X ; (2, 2) :: X .
endfm
