set show timing off .

load ../../contrib/systems/caut.maude

fmod 5x5GRID is
    including PERIODIC-GRID .

    vars S U D L R : State .

    --- calculate the next state as a function of the neighborhood

    eq width  = 3 .
    eq height = 3 .
    eq S -> up[X] down[X] left[L] right[R] = S -> X .
    eq S -> up[U] down[D] left[-] right[X] = S -> X .
    eq - -> up[-] down[X] left[-] right[-] = - -> X .
    eq S -> up[U] down[D] left[L] right[R] = S -> - [owise] .

    --- generate a random 5X5 grid

    var N : Nat .

    op init : Nat -> Culture .
    --------------------------
    eq init(0)
     = (0, 0) :: - ; (0, 1) :: X ; (0, 2) :: -
     ; (1, 0) :: X ; (1, 1) :: - ; (1, 2) :: -
     ; (2, 0) :: X ; (2, 1) :: X ; (2, 2) :: X .
endfm
