set show timing off .

mod BAZ is
  sort Foo .
  ops f g h : Foo -> Foo .
  ops i j k : Foo Foo -> Foo .

vars X Y Z W A B C D : Foo .
  eq j(f(X), Y) = i(f(Y), X) [variant] .
  rl g(i(X, k(Y, Z))) => f(k(Z, X)) .
  rl f(k(X, X)) => h(X) .
endm

set show breakdown on .

vu-narrow in BAZ : g(j(A, B)) =>* C .
vu-narrow in BAZ : g(j(A, B)) =>+ C .
vu-narrow in BAZ : g(j(A, B)) =>! C .

vu-narrow [,1] in BAZ : g(j(A, B)) =>! C .
vu-narrow [,2] in BAZ : g(j(A, B)) =>! C .
vu-narrow [,3] in BAZ : g(j(A, B)) =>! C .
vu-narrow [,4] in BAZ : g(j(A, B)) =>! C .

vu-narrow [,1] in BAZ : g(j(A, B)) =>* C .
vu-narrow [,2] in BAZ : g(j(A, B)) =>* C .
vu-narrow [,3] in BAZ : g(j(A, B)) =>* C .
