  fmod PRINT-ATTRIBUTE-EX is  
    sorts Foo FooList .  
    ops a b : -> Foo [ctor] .  
    subsort Foo < FooList .  
    op nil : -> FooList [ctor] .  
    op __ : FooList FooList -> FooList [ctor assoc id: nil] .  
 
    op reverse : FooList -> FooList .  
    eq reverse(nil) = nil .  
    ceq reverse(foo:Foo fl:FooList) 
      = fl':FooList
      if fl:FooList =/= nil
      /\ fl':FooList := reverse(fl:FooList) foo:Foo  
      /\ fl'':FooList := reverse(fl:FooList) foo:Foo  
      [print "first = " foo:Foo ", rest = " fl:FooList] .  
  endfm
  
  set print attribute on .

  red in PRINT-ATTRIBUTE-EX : reverse(a b a b) .
   