  ---- from the book All About Maude
  ---- by the Maude team

  load bakery.maude
  load model-checker.maude
  
  mod BAKERY-PREDS is 
    protecting BAKERY . 
    including SATISFACTION .
    subsort BState < State .
    ops 1wait 2wait 1crit 2crit : -> Prop [ctor] .
    vars P Q : Mode .
    vars X Y : Nat .
    eq < wait, X, Q, Y > |= 1wait = true .
    eq < sleep, X, Q, Y > |= 1wait = false .
    eq < crit, X, Q, Y > |= 1wait = false .
    eq < P, X, wait, Y > |= 2wait = true .
    eq < P, X, sleep, Y > |= 2wait = false .
    eq < P, X, crit, Y > |= 2wait = false .
    eq < crit, X, Q, Y > |= 1crit = true .
    eq < sleep, X, Q, Y > |= 1crit = false .
    eq < wait, X, Q, Y > |= 1crit = false .
    eq < P, X, crit, Y > |= 2crit = true .
    eq < P, X, sleep, Y > |= 2crit = false .
    eq < P, X, wait, Y > |= 2crit = false .
  endm
