  ---- from the book All About Maude
  ---- by the Maude team

  fmod NAT-PRED-KIND is
    sort Nat .
    op 0 : -> Nat [ctor] .
    op s_ : Nat -> Nat [ctor] .
    op p_ : Nat -> [Nat] .
    op _+_ : Nat Nat -> Nat [comm] .
    vars N M : Nat .
    eq N + 0 = N .
    eq (s N) + (s M) = s s (N + M) .
    eq p s N = N .
  endfm
    
***(
Maude> red p 0 .
reduce in NAT-PRED-KIND : p 0 .
rewrites: 0 in 0ms cpu (0ms real) (~ rewrites/second)
result [Nat]: p 0
    
Maude> red p s s 0 .
reduce in NAT-PRED-KIND : p s s 0 .
rewrites: 1 in 0ms cpu (0ms real) (~ rewrites/second)
result Nat: s 0
    
Maude> red p s s 0 + s p 0 .
reduce in NAT-PRED-KIND : s p 0 + p s s 0 .
rewrites: 1 in 0ms cpu (0ms real) (~ rewrites/second)
result [Nat]: s 0 + s p 0
)    