#!/bin/sh

MAUDE_LIB=$srcdir/../../../src/Main
export MAUDE_LIB

../../../src/Main/maude \
  < cterms.maude -no-banner -no-advise \
  > cterms.out 2>&1

diff cterms.expected cterms.out > /dev/null 2>&1
