#!/bin/sh

MAUDE_LIB=$srcdir/../../../src/Main
export MAUDE_LIB

../../../src/Main/maude \
  < metalevel-ext.maude -no-banner -no-advise \
  > metalevel-ext.out 2>&1

diff metalevel-ext.expected metalevel-ext.out > /dev/null 2>&1
