#!/bin/sh

MAUDE_LIB=$srcdir/../../../src/Main
export MAUDE_LIB

../../../src/Main/maude \
  < mtemplate.maude -no-banner -no-advise \
  > mtemplate.out 2>&1

diff mtemplate.expected mtemplate.out > /dev/null 2>&1
