#!/bin/sh

MAUDE_LIB=$srcdir/../../../src/Main
export MAUDE_LIB

../../../src/Main/maude \
  < unification.maude -no-banner -no-advise \
  > unification.out 2>&1

diff unification.expected unification.out > /dev/null 2>&1
