#!/bin/sh

MAUDE_LIB=$srcdir/../../../src/Main
export MAUDE_LIB

../../../src/Main/maude \
  < $srcdir/sk2-2.maude -no-banner -no-advise \
  > sk2-2.out 2>&1

diff $srcdir/sk2-2.expected sk2-2.out > /dev/null 2>&1
