#!/bin/sh

MAUDE_LIB=$srcdir/../../../src/Main
export MAUDE_LIB

../../../src/Main/maude \
  < $srcdir/unordered-channel.maude -no-banner -no-advise \
  > unordered-channel.out 2>&1

diff $srcdir/unordered-channel.expected unordered-channel.out > /dev/null 2>&1
