#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  $srcdir/marc3-17-09.maude -no-banner -no-advise \
  > marc3-17-09.out 2>&1

diff $srcdir/marc3-17-09.expected marc3-17-09.out > /dev/null 2>&1
