***(
Bug reported by Francisco Duran <duran@lcc.uma.es>
Received 10/6/09.

Crash due to unification sort computations producing out-of-range sort
indices for free, fresh variables. Caused by BDD computations not
constraining the values of these indices to be valid, because of their
freshness.

Resolved in alpha92a.
)

set show timing off .

red in META-LEVEL :
metaUnify(mod 'MINT-3-CLEARFROZEN-EQS2RLS-ADDEDRLS-REMOVED-ID-SYMBOLS-CLEARFROZEN-EQS2RLS-REMOVED-ID-SYMBOLS is
   nil
   sorts '#EqCondition ; 'Bool ; 'Int ; 'Nat ; 'NzInt ; 'NzNat ; 'Zero .
   subsort 'Nat < 'Int .
   subsort 'NzInt < 'Int .
   subsort 'NzNat < 'Nat .
   subsort 'NzNat < 'NzInt .
   subsort 'Zero < 'Nat .
   op '#_#_# : 'Int '#EqCondition -> 'Int [none] .
   op '#_#_#_# : '`[Int`] '`[Int`] '#EqCondition -> '`[Int`] [none] .
   op '-_ : 'Int -> 'Int [none] .
   op '-_ : 'NzInt -> 'NzInt [none] .
   op '0 : nil -> 'Zero [none] .
   op '_*_ : 'Int 'Int -> 'Int [assoc comm] .
   op '_*_ : 'Nat 'Nat -> 'Nat [assoc comm] .
   op '_*_ : 'NzInt 'NzInt -> 'NzInt [assoc comm] .
   op '_*_ : 'NzNat 'NzNat -> 'NzNat [assoc comm] .
   op '_+_ : 'Int 'Int -> 'Int [assoc comm] .
   op '_+_ : 'Nat 'Nat -> 'Nat [assoc comm] .
   op '_/\_ : '#EqCondition '#EqCondition -> '#EqCondition [none] .
   op '_=E1=_ : 'Int 'Int -> 'Bool [none] .
   op '_=_ : '`[Bool`] '`[Bool`] -> '#EqCondition [none] .
   op '_>_ : 'Nat 'Nat -> 'Bool [none] .
   op '_and_ : 'Bool 'Bool -> 'Bool [assoc comm prec(55)] .
   op '_or_ : 'Bool 'Bool -> 'Bool [assoc comm prec(59)] .
   op 'd : 'Nat 'Nat -> 'Nat [comm] .
   op 'false : nil -> 'Bool [ctor special(
     id-hook('SystemFalse, nil))] .
   op 'gcd : 'NzInt 'NzInt -> 'NzNat [comm] .
   op 'gcd : 'NzNat 'NzNat -> 'NzNat [comm] .
   op 'nil : nil -> '#EqCondition [none] .
   op 'not_ : 'Bool -> 'Bool [prec(53)] .
   op 'p_ : 'NzNat -> 'Nat [none] .
   op 'quot : 'Int 'NzInt -> 'Int [none] .
   op 'quot : 'Nat 'NzNat -> 'Nat [none] .
   op 's_ : 'Nat -> 'NzNat [none] .
   op 'true : nil -> 'Bool [ctor special(
     id-hook('SystemTrue, nil))] .
   none
   none
   none
endm, '_+_['M':NzNat,'_+_['-_['N':NzNat],'X@@@:`[Int`]]] =? '_+_['0.Zero,'#4:`[Int`]], 5, 1) .
