#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/paco10-6-09.maude -no-banner -no-advise \
  > paco10-6-09.out 2>&1

diff $srcdir/paco10-6-09.expected paco10-6-09.out > /dev/null 2>&1
