#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/santiago9-21-09.maude -no-banner -no-advise \
  > santiago9-21-09.out 2>&1

diff $srcdir/santiago9-21-09.expected santiago9-21-09.out > /dev/null 2>&1
