#!/bin/sh

MAUDE_LIB=$srcdir/../../src/Main
export MAUDE_LIB

../../src/Main/maude \
  < $srcdir/traian8-12-09.maude -no-banner -no-advise \
  > traian8-12-09.out 2>&1

diff $srcdir/traian8-12-09.expected traian8-12-09.out > /dev/null 2>&1
